language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - j.bernal@upm.es
services:
  - mongodb
script:
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify # Test unitarios y de integracion con covertura

# Subir a sonarcloud
- mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=miw-upm-github -Dsonar.login=$SONAR

# Desplegar en Heroku
deploy: # https://template-spring5.herokuapp.com/v2/api-docs
  provider: heroku
  api_key:
    secure: $HEROKU
